### ISSUE TITLE
Cannot read a bunch of W3C valid feeds because of content type

### ISSUE THREAD

**Issue by adadgio** [simplepie/simplepie#597] opened 2018-10-15 14:08 UTC
It seems the library cannot parse prefectly valid RSS feed due to content type such as : 

`application/rss+xml, application/rdf+xml;q=0.8, application/atom+xml;q=0.6, application/xml;q=0.4, text/xml;q=0.4`

The full error is 

```
PHP Notice: A feed could not be found at `http://rss.sciencedirect.com/publication/science/12783218`; the status code is `200` and content-type is `application/rss+xml, application/rdf+xml;q=0.8, application/atom+xml;q=0.6, application/xml;q=0.4, text/xml;q=0.4` in <EDITED>/vendor/simplepie/simplepie/library/SimplePie.php on line 1673
```

The feed URL is https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frss.sciencedirect.com%2Fpublication%2Fscience%2F12783218

**Comment by adadgio** [comment] 2018-10-15 14:14
PS: the parser feed works with the force_feed option enforced to TRUE.

**Comment by skyzyx** [comment] 2018-10-15 16:28
There are many things that are important to RSS and Atom feeds that are outside of the XML itself.

The Content-Type headers are used to determine whether SimplePie has been handed a feed or not so that it doesn’t waste time trying to parse something it can’t. In this case, those content-type headers are invalid.

Using `force_feed()` bypasses this preventative check.

What you have described here is not a bug since SimplePie is functioning as designed. The server told us that this was not a feed (invalid content-type), and SimplePie trusted that the server was telling the truth.

Resolving.

**Closed by skyzyx** 2018-10-15 16:28 UTC
