### ISSUE TITLE
Feature Request: JSON Feed support

### ISSUE THREAD

**Issue by rajjanorkar** [simplepie/simplepie#549] opened 2017-10-17 01:16 UTC
Would be awesome if simplepie support parsing [JSON feeds](https://jsonfeed.org/). Publishing and parsing them is much more straightforward and lightweight compared to RSS and Atom, and adoption is starting to pick up.

**Comment by jtojnar** [comment] 2017-11-29 11:43
Duplicate of #519

**Closed** 2018-01-25 20:44 UTC
Labels: Duplicate
