### ISSUE TITLE
Simplepie not working for this valid feed

### ISSUE THREAD

**Issue by abhij89** [simplepie/simplepie#563] opened 2017-12-07 14:48 UTC
Feed url is https://jonathan.biz/feed

It says "cURL error 22: The requested URL returned error: 400 Bad Request" although i validated the url on w3c validator and feedvalidator, both says feed is valid and works fine..please suggest?

**Comment by abhij89** [comment] 2017-12-07 14:49
![2017-12-07_2010](https://user-images.githubusercontent.com/15982920/33721056-da4b88ec-db8b-11e7-8257-89bd4bb3c6e6.png)

**Comment by skyzyx** [comment] 2017-12-07 18:41
Sounds like a duplicate of https://github.com/simplepie/simplepie/issues/562. Your host may be blocking the word "SimplePie" in the user-agent. You'll need to ask them to stop blocking it, or you can update your own code to update your SimplePie user-agent with [SimplePie::user_agent()](https://github.com/simplepie/simplepie/blob/7f832bec90e68e91ae9b852db1ef71de6c0c9f7c/library/SimplePie.php#L1112-L1115).

**Closed by skyzyx** 2017-12-07 18:41 UTC
